[package]
name = "turbina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.9.2"
once_cell = "1.20.2"
regex = "1.11.1"
rstest = "0.24.0"
